# Generated by Django 5.0.1 on 2024-01-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('first', models.CharField(max_length=20)),
                ('second', models.CharField(max_length=20)),
                ('army', models.BooleanField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('point', models.CharField(max_length=20)),
                ('places', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.university')),
            ],
        ),
    ]
