# Generated by Django 5.0.1 on 2024-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='army',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
