# Generated by Django 5.0.1 on 2024-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0002_alter_university_army_alter_university_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='second',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
