# Generated by Django 5.0.1 on 2024-01-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0003_alter_university_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='army',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='university',
            name='second',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
