# Generated by Django 5.0.1 on 2024-01-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0004_alter_university_army_alter_university_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='army',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
